### ISSUE TITLE
request superagent cors issue

### ISSUE THREAD

**Issue by smhall05** [eman1000/TaxiApp#1]
I am unable to use the request util per the below:

07-21 21:38:24.307 16503 18585 I ReactNativeJS: 'ERR request: ', { [Error: Request has been terminated
07-21 21:38:24.307 16503 18585 I ReactNativeJS: Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.]
07-21 21:38:24.307 16503 18585 I ReactNativeJS:   crossDomain: true,
07-21 21:38:24.307 16503 18585 I ReactNativeJS:   status: undefined,
07-21 21:38:24.307 16503 18585 I ReactNativeJS:   method: 'POST',
07-21 21:38:24.307 16503 18585 I ReactNativeJS:   url: 'http://localhost:3000/api/bookings' }

I am using an android emulator, is there anything special that needs to be done? The above was achieved by changing request.js to:

request.Request.prototype.finish = function (callback) {
    // this replaces superagent's .end() function to include our custom error handling (see above)
    this.end((err,res)=>{
        console.log("ERR request: ",err),
        callback(err,res);
    });
};

**Comment by smhall05** [comment]
It turns out I needed to add the following line inside my router.post and router.get for bookings.js on the server:

res.header("Access-Control-Allow-Origin", "http://localhost:8081");

Any idea why you didn't have to add this at all and yet it still worked for you? This issue can be closed, but I am curious as to why. Thanks again for putting this series together.

**Comment by smhall05** [comment]
The real issue had nothing to do with cors. I was still hitting the issue, the below explains that for Android I have to use the IP address of my machine since it is an emulator as opposed to iOS which is a simulator. Hope this helps someone else:
-----
The thing is, that iOS is running in a simulator and Android is running in an emulator.
The localhost is pointing to the environment in which the code is running. The emulator emulates a real device while the simulator is only imitating the device.
Therefore the localhost on Android is pointing to the emulated Android device. And not to the machine on which your server is running.
The solution is to replace localhost with the IP address of your machine.

**Comment by jitendarkumars** [comment]
I changed localhost to my machine IP and it worked for me....
